mac80211: fix missing symbol and compilation with mips
The "MAC80211_RC_MINSTREL_DEBUGFS_API=" was missing in local-symbols.

Further, the compilation failed on mips with
  ERROR: modpost: "__udivdi3" [/home/leecher/Desktop/Coding-Area/openwrt_ervenet_bluse_mac/openwrt/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/backports-6.1-rc8/net/mac80211/mac80211.ko] undefined!

Fix it by casting to u32.

Signed-off-by: Nick Hainke <vincent@systemli.org>